### PR TITLE
Fix Deprecation API call in Rails 5.

### PR DESCRIPTION
**Pull request by huacnlee**
> DEPRECATION WARNING: Passing a column to `quote` has been deprecated. It is only used for type casting, which should be handled elsewhere. See https://github.com/rails/arel/commit/6160bfbda1d1781c3b08a33ec4955f170e95be11 for more information.

### CODE REVIEW

**Comment by jamis** [comment]
Thank you for this! This looks like a good step in the right direction.

However (and I may be misunderstanding this), wouldn't this just result in every value being quoted as a string, regardless of it's type? It looks like there is a new API, connection.type_cast(value, column), and we should detect whether that method exists, and use it if so, rather than just hoping that the value given happens to be the right type for insertion.

**Comment by huacnlee** [comment]
@jamis I have updated.

**Comment by kaluznyo** [comment]
Any update on this ?

**Comment by jamis** [comment]
Thank you! Sorry I dropped the ball on this.

**Pull request merged**
