### PR TITLE
Add CI on pull requests / merges

### PR DESCRIPTION
**Pull request by mberlanda**
Hey @jamis , it would be nice to have some code checks on PR and pushes. 
 created a dummy default travis config file to integrate the repo in travis. Please feel free to close this PR if you prefer any other CI tool

### CODE REVIEW

**Comment by jamis** [comment]
Great suggestion! Thanks!

**Comment by mberlanda** [comment]
You may need to create the project o Travis CI ad well

**Comment by jamis** [comment]
Okay, well, I'll admit my experience with Travis CI is pretty minimal. I've set it up and got it to run a build, and the jobs for Ruby versions 2.2, 2.3, 2.4, and 2.5 all pass just fine. However, the job for "latest" fails, because "Unknown ruby interpreter version (do not know how to handle): latest."

I don't see any provision for "latest" in the Travis docs, but it's entirely possibly I'm misreading them. If you're aware of something I might have done wrong, or if there was a typo in the commit you made, let me know. Otherwise I'll just yank that "latest" line from the travis config.

**Comment by mberlanda** [comment]
Actually this was my mistake. As I did in this gem https://github.com/mberlanda/jsonschema_serializer/blob/master/.travis.yml I should have put `ruby-head` instead of latest. Sorry. It was a silly error. It may be useful to make a small commit to correct it

**Comment by mberlanda** [comment]
It looks fine now: https://travis-ci.org/jamis/bulk_insert
:sunglasses:

**Pull request merged**
